# Generated by Django 2.1.2 on 2018-10-31 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classact_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='classroom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classact_app.Classroom'),
        ),
    ]
