# Generated by Django 2.1.2 on 2018-11-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classact_app', '0004_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
