# Generated by Django 2.1.2 on 2018-11-23 23:45

import classact_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classact_app', '0008_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=classact_app.models.get_image_path),
        ),
    ]
