# Generated by Django 2.1.2 on 2018-11-30 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classact_app', '0009_auto_20181127_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndorseResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classact_app.Classroom')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classact_app.Response')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
